### ISSUE TITLE
driver.quit() for android - moved it into a promise in world.js

### ISSUE THREAD

**Issue by will675** [Matt-B/cucumber-js-selenium-webdriver-example#3]
Hi - was going to try to do a pull request but can't seem to create a branch to put this change into (tried creating one locally but it won't then let me push it to the origin and create one then either).  

I have been playing around trying to get Appium to work with the Android setup, but for a simulator.  Managed to get it working (just a case of figuring out that I need the simulator running as well as the server) but it wasn't closing the browser instance on the device, until I moved the driver.quit() line into a promise:
`this.registerHandler('AfterFeatures', function (event, callback) {
        driver.quit()
            .then(function () {
                callback();
            });
    });`

Sorry for the awful formatting but can't get github to behave.  Thanks for this setup though, given me a big step forward with Appium, really struggled to get to grips with it using just their docs!

**Comment by Matt-B** [comment]
Thank you for this! I've just committed this change into master - feel free to take a look and make sure I've interpreted it correctly. In the long term I'm hoping to get the Android stuff running in CI via something like Sauce Labs, which will hopefully catch issues like this.

If you have any other feedback, feel free to submit issues or PRs.
