### ISSUE TITLE
Could you please migrate cucumber version from 0.x to 2.X

### ISSUE THREAD

**Issue by thangakumard** [Matt-B/cucumber-js-selenium-webdriver-example#7]
@Matt-B - Could you please migrate cucumber version from 0.x to 2.X. If I migrate this project from cucumber version 0.x to 2.x browser is not launching. I am using ES2015 and latest version of cucumber& selenium-webdriver. Thanks in advance !

**Comment by Matt-B** [comment]
@thangakumard Sorry this took so long. I've merged quite a few changes into master which should update the project to use cucumber 2.3.1. I did try updating to cucumber 3 but I ran into an issue with hooks which I believe there is an open PR for. Once that is fixed I'll update cucumber again.
